apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-eats-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      name: go-eats-ml
  template:
    metadata:
      labels:
        name: go-eats-ml
    spec:
      containers:
        - name: go-eats-ml
          image: bentohset/go-eats-ml:latest
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: go-eats-ml
spec:
  type: ClusterIP
  selector:
    name: go-eats-ml
  ports:
    - protocol: TCP
      port: 83
      targetPort: 50051
