apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-eats-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: go-eats-bot
  template:
    metadata:
      labels:
        name: go-eats-bot
    spec:
      containers:
        - name: go-eats-bot
          image: bentohset/go-eats-bot:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: go-eats-bot
spec:
  type: ClusterIP
  selector:
    name: go-eats-bot
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8080